name: govegan_organics
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  http: ^1.2.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  gap: ^3.0.1
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^6.0.1
  image_picker: ^1.0.8
  geolocator: ^11.0.0
  video_player: ^2.8.6
  expandable_text: ^2.3.0
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.2.1


 

 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true


  assets:
    - images/
    - videos/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #