import 'dart:math';

var nameRam = [
  "Rahul",
  "Kalyani",
  "Eshika",
  "Geetika",
  "sonia",
  "Arya",
  "Meera",
  "Mishka",
  "Alisha",
  "	Naina",
  "Prisha",
  "  Rani",
  "Rebecca",
  "  Ryka",
  "  Sahana",
  "  Saloni",
  "Sanjana",
  "Shanaya",
  "Simran",
  "Advika"
];
var placeRam = [
  "Hyderabad",
  "Secunderabad",
  " Nizamabad",
  "Suryabagh",
  " Nausena Baugh",
  "Guntur",
  " Nellore",
  "Chittoor",
  "Eluru",
  "Anantapur",
  "Markapur",
  "Atchutapuram",
  " Hinjawadi",
  "Vaibhavwadi",
  "Kurduwadi",
  "Sanaswadi",
  "Sawantwadi",
  "Wadi",
  "Darewadi"
];
var itemRam = [
  "Chilli Powder",
  "Cinammon Powder",
  "Cardamom Powder",
  "Pepper Powder",
  "Fenugreek Powder",
  "Cumin Powder",
  "Cassia Powder",
  "Dill Powder",
  "Ginger Powder",
  "Poppy Powder",
  "Celery Powder",
  "Coriander Powder",
  "Fennel Powder",
  "Mustard Powder",
  "Tamarind Powder",
  "Oregano Powder",
  'Kokam Powder',
  'urmeric Powder',
  'Thyme Powder',
  'Saffron Powder'
];
var catRam = [
  "Spices",
  'Staples',
  "Oils",
  "Spices",
  'Staples',
  "Oils",
  "Spices",
  'Staples',
  "Oils",
  "Spices",
  'Staples',
  "Oils",
  "Spices",
  'Staples',
  "Oils",
  "Spices",
  "Oils",
  'Staples',
  "Oils",
  "Spices",
];
var subcatRam = [
  'Whole Spices',
  'Raw Spices',
  'Pulses',
  'Whole Spices',
  'Grains',
  'Millets',
  'Whole Spices',
  'Flour',
  'Rava',
  'General Oils',
  'Whole Spices',
  'Raw Spices',
  'Pulses',
  'Whole Spices',
  'Grains',
  'Millets',
  'Whole Spices',
  'Flour',
  'Rava',
  'General Oils',
];
var filterRam = [
  'Chilli powder/karam podi/laal mirch powder',
  'Cinnamon powder/dalchina Chakka Podi/dalchini chooran',
  'Cardamom powder/elakula podi/ilaychi powder',
  'Pepper powder/miriyala podi/kali mirch powder ',
  'Fenugreek powder/menthi podi/methi powder',
  'Cumin powder/jilakara podi/jeera chooran',
  'Cassia powder/kasiya podi/kaisiya powder',
  'Dill powder/menthula podi/dil powder',
  'Ginger powder/allam podi/adrak powder',
  'Poppy powder/gasagasalu podi/apheem powder',
  'Celery powder/vamaku podi/ajamoda powder',
  'Coriander powder/kotthimeera podi/dhaniya powder',
  'Fennel powder/sompu podi/sonph powder',
  'Mustard powder/avala podi/sarson ka powder',
  'Tamarind powder/chintha pandu podi/imli powder',
  'Oregano powder/oregano podi/oregano powder',
  'Kokam powder/kokam podi/kokam powder',
  'Turmeric powder/pasupu podi/haldhi powder',
  'Thyme powder/ajvain podi/ajvayaan ke phool powder',
  'Saffron powder/kumkumapuvvu podi/kesar powder',
];

int generateRandomNumber(int RanNumb, int startDigits) {
  Random random = Random();
  return random.nextInt(RanNumb) +
      startDigits; 
}
